package vista;

import controlador.utilidades.Colores;
import controlador.utilidades.Menu;
import controlador.ventanas.CInicial;

import proyecto.Proyecto;

public class Vperifericos extends javax.swing.JFrame {

    Menu m = new Menu(Proyecto.img);

    boolean derecha = false;

    public Vperifericos() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfdetalles = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtdetmarca = new javax.swing.JLabel();
        txtdetmodelo = new javax.swing.JLabel();
        txtdetserial = new javax.swing.JLabel();
        txtdetestado = new javax.swing.JLabel();
        txtdetususario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtperifericos1 = new javax.swing.JTable();
        txtdetdepar = new javax.swing.JLabel();
        jfañadir = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        txtreasigserial = new javax.swing.JLabel();
        txtreasigperi = new javax.swing.JLabel();
        txtserialperi = new javax.swing.JTextField();
        txtserialpc = new javax.swing.JTextField();
        cbtipoperi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnreasignar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jftipo = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtnuevoperi = new javax.swing.JTextField();
        btnnuevoperi = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();
        txtus = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtperifericos = new javax.swing.JTable();
        btnabriragregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnabrirReasignar = new javax.swing.JButton();
        btndetalles = new javax.swing.JButton();
        cbtipobusqueda = new javax.swing.JComboBox<>();
        cbbuscar = new javax.swing.JComboBox<>();
        txtbuscar = new javax.swing.JTextField();
        btntipo = new javax.swing.JButton();
        txtequipo = new javax.swing.JLabel();
        btnequipos = new javax.swing.JLabel();
        txtusuarios = new javax.swing.JLabel();
        btnusuarios = new javax.swing.JLabel();
        txtgraficas = new javax.swing.JLabel();
        btngraficas = new javax.swing.JLabel();
        txtAtras = new javax.swing.JLabel();
        btnsalir2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel2.setBackground(Colores.GRIS_CLARO);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Detalles");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, 40));

        txtdetmarca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdetmarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdetmarca.setText("Marca");
        jPanel2.add(txtdetmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, -1));

        txtdetmodelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdetmodelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdetmodelo.setText("modelo");
        jPanel2.add(txtdetmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, -1));

        txtdetserial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdetserial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdetserial.setText("serial");
        jPanel2.add(txtdetserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, -1));

        txtdetestado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdetestado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdetestado.setText("estado");
        jPanel2.add(txtdetestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, -1));

        txtdetususario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdetususario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdetususario.setText("usuario");
        jPanel2.add(txtdetususario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, -1));

        jtperifericos1.setBackground(new java.awt.Color(225, 232, 236));
        jtperifericos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Periferico", "Serial"
            }
        ));
        jtperifericos1.setShowHorizontalLines(false);
        jScrollPane2.setViewportView(jtperifericos1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, 200));

        txtdetdepar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdetdepar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdetdepar.setText("departamento");
        jPanel2.add(txtdetdepar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 350, -1));

        jfdetalles.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(Colores.GRIS_CLARO);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtreasigserial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtreasigserial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtreasigserial.setText("serial");
        jPanel1.add(txtreasigserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, -1));

        txtreasigperi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtreasigperi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtreasigperi.setText("perifericoo");
        jPanel1.add(txtreasigperi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, -1));

        txtserialperi.setBackground(new java.awt.Color(225, 232, 236));
        txtserialperi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtserialperi.setBorder(null);
        jPanel1.add(txtserialperi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        txtserialpc.setBackground(Colores.GRIS_CLARO);
        txtserialpc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtserialpc.setBorder(null);
        jPanel1.add(txtserialpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 140, -1));

        cbtipoperi.setBackground(Colores.GRIS_CLARO);
        cbtipoperi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbtipoperi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbtipoperi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoperiActionPerformed(evt);
            }
        });
        jPanel1.add(cbtipoperi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Serial de la PC:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo de periferico:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Serial del periferico:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, -1));

        btnagregar.setBackground(Colores.AZUL);
        btnagregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("Guardar");
        btnagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        btnreasignar.setBackground(Colores.AZUL);
        btnreasignar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnreasignar.setForeground(new java.awt.Color(255, 255, 255));
        btnreasignar.setText("Reasignar");
        btnreasignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnreasignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregra Periferico");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 350, -1));

        jfañadir.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(Colores.GRIS_CLARO);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nuevo tipo de periferico");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 20));

        txtnuevoperi.setBackground(Colores.GRIS_CLARO);
        txtnuevoperi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnuevoperi.setBorder(null);
        txtnuevoperi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnuevoperiActionPerformed(evt);
            }
        });
        jPanel3.add(txtnuevoperi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, -1));

        btnnuevoperi.setBackground(Colores.ROJO);
        btnnuevoperi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnnuevoperi.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevoperi.setText("Guardar");
        btnnuevoperi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnnuevoperi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jftipo.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(225, 232, 236));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtus.setForeground(new java.awt.Color(255, 255, 255));
        txtus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtus.setText("5");
        fondo.add(txtus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 120, 20));

        Separador.setForeground(new java.awt.Color(255, 255, 255));
        fondo.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 160, 20));

        jScrollPane1.setBackground(new java.awt.Color(225, 232, 236));

        jtperifericos.setBackground(new java.awt.Color(225, 232, 236));
        jtperifericos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Serial", "Periferico", "PC Asignada"
            }
        ));
        jtperifericos.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jtperifericos);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 430, 480));

        btnabriragregar.setBackground(Colores.ROJO);
        btnabriragregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnabriragregar.setForeground(new java.awt.Color(255, 255, 255));
        btnabriragregar.setText("Agregar");
        btnabriragregar.setToolTipText("");
        btnabriragregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnabriragregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabriragregarActionPerformed(evt);
            }
        });
        fondo.add(btnabriragregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 244, 145, 30));

        btneliminar.setBackground(Colores.ROJO);
        btneliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.setToolTipText("");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondo.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 359, 145, 30));

        btnabrirReasignar.setBackground(Colores.ROJO);
        btnabrirReasignar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnabrirReasignar.setForeground(new java.awt.Color(255, 255, 255));
        btnabrirReasignar.setText("Reasignar");
        btnabrirReasignar.setToolTipText("");
        btnabrirReasignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondo.add(btnabrirReasignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 244, 145, 30));

        btndetalles.setBackground(Colores.ROJO);
        btndetalles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndetalles.setForeground(new java.awt.Color(255, 255, 255));
        btndetalles.setText("Detalles");
        btndetalles.setToolTipText("");
        btndetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondo.add(btndetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 359, 145, 30));

        cbtipobusqueda.setBackground(Colores.AZUL);
        cbtipobusqueda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbtipobusqueda.setForeground(new java.awt.Color(255, 255, 255));
        cbtipobusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar", "Serial", "Periferico", "PC" }));
        cbtipobusqueda.setToolTipText("");
        cbtipobusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbtipobusqueda.setFocusable(false);
        fondo.add(cbtipobusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 120, 30));

        cbbuscar.setBackground(Colores.AZUL);
        cbbuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbuscar.setForeground(new java.awt.Color(255, 255, 255));
        cbbuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbuscar.setFocusable(false);
        cbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbuscarActionPerformed(evt);
            }
        });
        fondo.add(cbbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 150, 30));

        txtbuscar.setBackground(Colores.AZUL);
        txtbuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtbuscar.setBorder(null);
        fondo.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 150, 30));

        btntipo.setBackground(Colores.AZUL);
        btntipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btntipo.setForeground(new java.awt.Color(255, 255, 255));
        btntipo.setText("Crear");
        btntipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondo.add(btntipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 488, 160, 30));

        txtequipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.add(txtequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, -1));

        btnequipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnequipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnequipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnequiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnequiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnequiposMouseExited(evt);
            }
        });
        fondo.add(btnequipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 135, 175, 50));

        txtusuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fondo.add(txtusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, -1));

        btnusuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnusuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnusuariosMouseExited(evt);
            }
        });
        fondo.add(btnusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 340, 175, 50));

        txtgraficas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.add(txtgraficas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 80, -1));

        btngraficas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btngraficas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngraficas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngraficasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btngraficasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btngraficasMouseExited(evt);
            }
        });
        fondo.add(btngraficas, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 270, 175, 50));

        txtAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.add(txtAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 90, -1));

        btnsalir2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnsalir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalir2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsalir2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsalir2MouseExited(evt);
            }
        });
        fondo.add(btnsalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 65, 175, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/PERIFERICOS.png"))); // NOI18N
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 563));

        getContentPane().add(fondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//boton equipo
    private void btnequiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnequiposMouseEntered
        Proyecto.img.bordes(btnequipos);
    }//GEN-LAST:event_btnequiposMouseEntered

    private void btnequiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnequiposMouseExited
        Proyecto.img.no_bordes(btnequipos);
    }//GEN-LAST:event_btnequiposMouseExited

    private void btnequiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnequiposMouseClicked
        m.equipos_click(this);
    }//GEN-LAST:event_btnequiposMouseClicked
//boton usuarios
    private void btnusuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuariosMouseEntered
        Proyecto.img.bordes(btnusuarios);
    }//GEN-LAST:event_btnusuariosMouseEntered

    private void btnusuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuariosMouseExited
        Proyecto.img.no_bordes(btnusuarios);
    }//GEN-LAST:event_btnusuariosMouseExited

    private void btnusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuariosMouseClicked
        m.usuarios_click(this);
    }//GEN-LAST:event_btnusuariosMouseClicked
//boton graficas
    private void btngraficasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngraficasMouseEntered
        Proyecto.img.bordes(btngraficas);
    }//GEN-LAST:event_btngraficasMouseEntered

    private void btngraficasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngraficasMouseExited
        Proyecto.img.no_bordes(btngraficas);
    }//GEN-LAST:event_btngraficasMouseExited

    private void btnsalir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalir2MouseClicked
        Inicial atras = Inicial.getInstance();
        CInicial ci = new CInicial(atras);
        this.setVisible(false);
    }//GEN-LAST:event_btnsalir2MouseClicked
//grafica click
    private void btngraficasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngraficasMouseClicked
        m.departamento_click(this);
    }//GEN-LAST:event_btngraficasMouseClicked

    private void cbtipoperiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoperiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoperiActionPerformed

    private void txtnuevoperiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnuevoperiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnuevoperiActionPerformed

    private void btnabriragregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabriragregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnabriragregarActionPerformed

    private void cbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbuscarActionPerformed

    private void btnsalir2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalir2MouseEntered
        Proyecto.img.bordes(btnsalir2);
    }//GEN-LAST:event_btnsalir2MouseEntered

    private void btnsalir2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalir2MouseExited
        Proyecto.img.no_bordes(btnsalir2);
    }//GEN-LAST:event_btnsalir2MouseExited

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vperifericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vperifericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vperifericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vperifericos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vperifericos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSeparator Separador;
    public javax.swing.JButton btnabrirReasignar;
    public javax.swing.JButton btnabriragregar;
    public javax.swing.JButton btnagregar;
    public javax.swing.JButton btndetalles;
    public javax.swing.JButton btneliminar;
    private javax.swing.JLabel btnequipos;
    private javax.swing.JLabel btngraficas;
    public javax.swing.JButton btnnuevoperi;
    public javax.swing.JButton btnreasignar;
    private javax.swing.JLabel btnsalir2;
    public javax.swing.JButton btntipo;
    private javax.swing.JLabel btnusuarios;
    public javax.swing.JComboBox<String> cbbuscar;
    public javax.swing.JComboBox<String> cbtipobusqueda;
    public javax.swing.JComboBox<String> cbtipoperi;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JFrame jfañadir;
    public javax.swing.JFrame jfdetalles;
    public javax.swing.JFrame jftipo;
    public javax.swing.JTable jtperifericos;
    public javax.swing.JTable jtperifericos1;
    private javax.swing.JLabel txtAtras;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JLabel txtdetdepar;
    public javax.swing.JLabel txtdetestado;
    public javax.swing.JLabel txtdetmarca;
    public javax.swing.JLabel txtdetmodelo;
    public javax.swing.JLabel txtdetserial;
    public javax.swing.JLabel txtdetususario;
    private javax.swing.JLabel txtequipo;
    private javax.swing.JLabel txtgraficas;
    public javax.swing.JTextField txtnuevoperi;
    public javax.swing.JLabel txtreasigperi;
    public javax.swing.JLabel txtreasigserial;
    public javax.swing.JTextField txtserialpc;
    public javax.swing.JTextField txtserialperi;
    public javax.swing.JLabel txtus;
    private javax.swing.JLabel txtusuarios;
    // End of variables declaration//GEN-END:variables
}
